"""Generate include/echo_params.h from sim/params.py (single source of truth).

Run from the repo root:  uv run python firmware/tools/gen_params_header.py
The firmware must never hold hand-copied physics/filter/gate numbers
(CLAUDE.md section 3: no magic numbers outside params).
"""

from dataclasses import replace
from pathlib import Path

import numpy as np

from sim.control import design_lqr_balance
from sim.estimator import (
    discretize,
    initial_covariance,
    measurement_matrix,
    measurement_noise,
    process_noise,
)
from sim.params import (
    default_disturbance_params,
    default_estimator_params,
    default_gate_params,
    default_lqr_balance_params,
    default_plant_params,
    default_run_params,
    default_sensor_params,
    default_tilt_gate_params,
)

OUT = Path(__file__).resolve().parents[1] / "include" / "echo_params.h"


def arr(name: str, a: np.ndarray) -> str:
    flat = ", ".join(f"{v:.17g}" for v in np.asarray(a).ravel())
    return f"static const double {name}[{np.asarray(a).size}] = {{{flat}}};"


def main() -> None:
    p, sp = default_plant_params(), default_sensor_params()
    ep, gp = default_estimator_params(), default_gate_params()
    tp, rp = default_tilt_gate_params(), default_run_params()
    dp = default_disturbance_params()
    dt = rp.dt_control
    Ad, Bd = discretize(p, dt)
    p_payload = replace(p, M=p.M + dp.payload_shift_delta_M, L=p.L + dp.payload_shift_delta_L)
    Ad_pl, Bd_pl = discretize(p_payload, dt)
    K = design_lqr_balance(p, default_lqr_balance_params())

    lines = [
        "// GENERATED by firmware/tools/gen_params_header.py from sim/params.py. DO NOT EDIT.",
        "#pragma once",
        "",
        f"static const double ECHO_DT = {dt!r};  // s, control/estimation loop (200 Hz)",
        f"static const double ECHO_V_BATT = {dp.battery_droop_v_nominal!r};  // V, nominal 2S LiPo",
        f"static const double ECHO_FALL_PSI = {rp.fall_psi_threshold!r};  // rad",
        f"static const double ECHO_SIGMA_GYRO = {sp.sigma_gyro!r};  // rad/s",
        f"static const double ECHO_SIGMA_ACCEL = {sp.sigma_accel!r};  // rad",
        f"static const double ECHO_GYRO_BIAS_WALK = {sp.gyro_bias_walk!r};  // rad/s/sqrt(s)",
        f"static const double ECHO_ENCODER_CPR = {float(sp.encoder_cpr)!r};  // PLACEHOLDER (CLAUDE.md 6.2)",
        f"static const int ECHO_GATE_N = {gp.N};",
        f"static const double ECHO_TAU1 = {gp.tau1!r};",
        f"static const double ECHO_TAU2 = {gp.tau2!r};",
        f"static const double ECHO_TAU1_EXIT = {gp.tau1_exit!r};",
        f"static const double ECHO_TAU2_EXIT = {gp.tau2_exit!r};",
        f"static const double ECHO_T_DWELL = {gp.T_dwell!r};  // s",
        f"static const double ECHO_TILT_PSI1 = {tp.psi1!r};",
        f"static const double ECHO_TILT_PSI2 = {tp.psi2!r};",
        f"static const double ECHO_TILT_PSI1_EXIT = {tp.psi1_exit!r};",
        f"static const double ECHO_TILT_PSI2_EXIT = {tp.psi2_exit!r};",
        f"static const double ECHO_TILT_T_DWELL = {tp.T_dwell!r};  // s",
        f"static const double ECHO_CAUTIOUS_SPEED_SCALE = {rp.cautious_speed_scale!r};",
        f"static const double ECHO_PUSH_KICK = {dp.push_magnitude!r};  // rad/s psi_dot kick",
        f"static const double ECHO_GYRO_BIAS_STEP = {dp.gyro_bias_fault_magnitude!r};  // rad/s",
        f"static const double ECHO_ACCEL_NOISE_MULT = {dp.accel_noise_fault_multiplier!r};",
        "// Row-major.  x = [theta, psi, theta_dot, psi_dot, b_g]; y = [theta_enc, psi_dot_gyro, psi_acc]",
        arr("ECHO_AD", Ad),
        arr("ECHO_BD", Bd),
        "// Virtual-robot true plant after a payload shift (M, L deltas from DisturbanceParams)",
        arr("ECHO_AD_PAYLOAD", Ad_pl),
        arr("ECHO_BD_PAYLOAD", Bd_pl),
        arr("ECHO_C", measurement_matrix()),
        arr("ECHO_Q", process_noise(sp, ep, dt)),
        arr("ECHO_R", measurement_noise(sp)),
        arr("ECHO_P0", initial_covariance(ep)),
        arr("ECHO_K_BALANCE", K),
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
